# Generated by Django 5.0.8 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_notice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardnotice",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="부제목"),
        ),
    ]
