# Generated by Django 5.0.8 on 2026-04-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("SPONSOR", "협찬 문의"), ("GENERAL", "일반 문의")], default="GENERAL", max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, default="")),
                ("company_name", models.CharField(blank=True, default="", max_length=200)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="inquiries/logos/")),
                ("status", models.CharField(choices=[("pending", "답변 대기"), ("answered", "답변 완료")], default="pending", max_length=20)),
                ("answer", models.TextField(blank=True, default="")),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_inquiries",
                        to="admin_accounts.adminmembership",
                    ),
                ),
            ],
            options={
                "db_table": "inquiry",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["type", "status"], name="inquiry_type_status_idx"),
                    models.Index(fields=["created_at"], name="inquiry_created_at_idx"),
                    models.Index(fields=["email"], name="inquiry_email_idx"),
                ],
            },
        ),
    ]
