# Generated by Django 5.0.8 on 2026-04-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("image_s3_key", models.CharField(blank=True, default="", help_text="S3 또는 로컬 MEDIA 경로 키 (sponsors/...). PlanDoc/s3Rules.md", max_length=1024)),
                ("image", models.ImageField(blank=True, null=True, upload_to="sponsors/", verbose_name="스폰서 이미지(레거시)")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sponsor",
                "ordering": ["sort_order", "id"],
                "indexes": [models.Index(fields=["is_active", "sort_order"], name="sponsor_is_activ_1fcb57_idx")],
            },
        ),
    ]
