# Generated by Django 5.0.8 on 2026-04-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sponsor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='inquiry_type_a3a35a_idx',
            old_name='inquiry_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='inquiry_created_5f8c93_idx',
            old_name='inquiry_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='inquiry_email_74014c_idx',
            old_name='inquiry_email_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsor',
            new_name='sponsor_is_acti_a6514e_idx',
            old_name='sponsor_is_activ_1fcb57_idx',
        ),
    ]
