"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root (backend/)
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", "1", "yes")

# Comma-separated list, e.g. "localhost,127.0.0.1,.api.b2n2027.org"
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]

if not DEBUG:
    if SECRET_KEY == "django-insecure-dev-key-change-in-production":
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is False.")
    if not ALLOWED_HOSTS or ALLOWED_HOSTS == ["localhost", "127.0.0.1"]:
        raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS must be configured for production.")

# nginx 등 리버스 프록시 뒤에서 X-Forwarded-Proto를 반영해 request.is_secure()·쿠키 Secure가 맞게 동작하도록
_behind_proxy = os.getenv("DJANGO_BEHIND_HTTPS_PROXY", "").strip().lower() in ("1", "true", "yes")
if _behind_proxy:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = os.getenv("DJANGO_USE_X_FORWARDED_HOST", "").strip().lower() in ("1", "true", "yes")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    # Local apps
    'apps.core',
    'apps.events',
    'apps.participants',
    'apps.admin_accounts',
    'apps.board_notice',
    'apps.homepage_doc',
    'apps.products',
    'apps.messages.apps.MessagesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


def _env_truthy(name: str) -> bool:
    return os.getenv(name, "").strip().lower() in ("1", "true", "yes", "on")


def _mysql_connection_options() -> dict:
    """mysqlclient에 넘길 OPTIONS. require_secure_transport=ON 이면 TLS 필요 (오류 3159)."""
    opts: dict = {
        "charset": "utf8mb4",
        "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
    }
    if not _env_truthy("DB_SSL_REQUIRED"):
        return opts

    ssl_ca = os.getenv("DB_SSL_CA", "").strip()
    if ssl_ca:
        opts["ssl"] = {"ca": ssl_ca}
        return opts

    for candidate in (
        "/etc/ssl/cert.pem",  # macOS 등
        "/etc/ssl/certs/ca-certificates.crt",  # Debian/Ubuntu
    ):
        if candidate and os.path.isfile(candidate):
            opts["ssl"] = {"ca": candidate}
            return opts

    # CA 경로를 못 찾으면 빈 ssl dict로 암호화만 시도 (클라우드·버전에 따라 DB_SSL_CA 설정 필요)
    opts["ssl"] = {}
    return opts


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "b2n2027"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": _mysql_connection_options(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS settings (comma-separated origins, e.g. "http://localhost:3000,http://localhost:3001")
_cors_origins = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003,"
    "https://dev.b2n2027.org,https://www.b2n2027.org,https://b2n2027.org,https://admin.b2n2027.org",
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",") if o.strip()]

CORS_ALLOW_CREDENTIALS = True
# 참가자 확인 PATCH 등 `X-Participant-Token` 사용 시 preflight에 헤더 허용 필요
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-participant-token",
]

# 관리자 JWT (frontend-admin)
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", SECRET_KEY)
JWT_ALGORITHM = "HS256"
JWT_ACCESS_EXPIRATION_DELTA = int(os.getenv("JWT_ACCESS_EXPIRATION_SECONDS", str(15 * 60)))  # 15분
JWT_REFRESH_EXPIRATION_DELTA = int(os.getenv("JWT_REFRESH_EXPIRATION_SECONDS", str(7 * 24 * 60 * 60)))  # 7일
ADMIN_JWT_REFRESH_COOKIE_NAME = os.getenv("ADMIN_JWT_REFRESH_COOKIE_NAME", "adminRefreshToken")
_admin_rd = os.getenv("ADMIN_JWT_REFRESH_COOKIE_DOMAIN", "").strip()
ADMIN_JWT_REFRESH_COOKIE_DOMAIN = _admin_rd or None
ADMIN_JWT_REFRESH_COOKIE_SAMESITE = os.getenv("ADMIN_JWT_REFRESH_COOKIE_SAMESITE", "Lax")
# 비우면 request.is_secure() 사용. 운영 HTTPS에서 명시하려면 True 권장(프록시 헤더와 함께)
_admin_cs = os.getenv("ADMIN_JWT_REFRESH_COOKIE_SECURE", "").strip().lower()
if _admin_cs in ("true", "1", "yes"):
    ADMIN_JWT_REFRESH_COOKIE_SECURE = True
elif _admin_cs in ("false", "0", "no"):
    ADMIN_JWT_REFRESH_COOKIE_SECURE = False
else:
    ADMIN_JWT_REFRESH_COOKIE_SECURE = None

# 이메일 (협찬 문의 등)
# 1) GMAIL_SENDER + GMAIL_APP_PASSWORD → Gmail SMTP (Google 계정 앱 비밀번호)
# 2) 그다음 EMAIL_HOST 등 일반 SMTP
# 3) 둘 다 없으면 콘솔 백엔드(개발용 출력)
_gmail_sender = os.getenv("GMAIL_SENDER", "").strip()
_gmail_app_password = os.getenv("GMAIL_APP_PASSWORD", "").strip()
_email_host = os.getenv("EMAIL_HOST", "").strip()

if _gmail_sender and _gmail_app_password:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = _gmail_sender
    EMAIL_HOST_PASSWORD = _gmail_app_password
elif _email_host:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = _email_host
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

_default_from = os.getenv("DEFAULT_FROM_EMAIL", "").strip()
if _default_from:
    DEFAULT_FROM_EMAIL = _default_from
elif _gmail_sender:
    DEFAULT_FROM_EMAIL = _gmail_sender
else:
    DEFAULT_FROM_EMAIL = "noreply@b2n2027.org"

SPONSOR_INQUIRY_TO = os.getenv("SPONSOR_INQUIRY_TO", "admin_kr@b2n2027.org")

# S3 (비공개 버킷 + Presigned URL) — PlanDoc/s3Rules.md / 상품 옵션 이미지 등
# 일부 .env 는 AWS_STORAGE_BUCKET_NAME / AWS_S3_REGION_NAME 만 쓰는 경우가 있어 별칭 허용
AWS_S3_BUCKET_NAME = (
    os.getenv("AWS_S3_BUCKET_NAME", "").strip() or os.getenv("AWS_STORAGE_BUCKET_NAME", "").strip()
)
AWS_S3_REGION = (
    os.getenv("AWS_S3_REGION", "").strip()
    or os.getenv("AWS_S3_REGION_NAME", "").strip()
    or "ap-northeast-2"
)
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "").strip()
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "").strip()
# Presigned GET 유효 시간(초). 비어 있으면 7일.
AWS_S3_PRESIGNED_GET_EXPIRES = int(os.getenv("AWS_S3_PRESIGNED_GET_EXPIRES", str(7 * 24 * 3600)))
# True: 스폰서·상품옵션 이미지 URL을 Presigned 대신 공개 HTTPS URL로 내림(버킷 정책으로 GetObject 허용 필요).
AWS_S3_PUBLIC_GET_FOR_MANAGED = _env_truthy("AWS_S3_PUBLIC_GET_FOR_MANAGED")
# True: 위가 켜져 있어도 항상 Presigned만 사용(공개 URL 403·깨진 썸네일일 때 임시로 1).
AWS_S3_FORCE_PRESIGNED_FOR_MANAGED = _env_truthy("AWS_S3_FORCE_PRESIGNED_FOR_MANAGED")
# True: 업로드 시 ACL public-read(버킷이 ACL 허용할 때만). ACL 막힌 버킷은 버킷 정책으로 공개.
AWS_S3_UPLOAD_ACL_PUBLIC_READ = _env_truthy("AWS_S3_UPLOAD_ACL_PUBLIC_READ")

# 알리고 문자 (관리자 메시지 모듈)
ALIGO_API_KEY = os.getenv("ALIGO_API_KEY", "").strip()
ALIGO_USER_ID = os.getenv("ALIGO_USER_ID", "").strip()

# 인증번호 등 단기 캐시 (로컬 메모리 — 단일 프로세스·개발용. 운영 다중 워커 시 Redis 권장)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "b2n-default-cache",
    }
}

# Google 클라우드 API 등 (메일 발송과 무관, 필요 시 앱 코드에서 사용)
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", "").strip()

# 로그 디렉터리 (파일 핸들러용, 없으면 생성)
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(parents=True, exist_ok=True)

# 로깅: 콘솔 + backend/logs/django.log (회전)
_LOG_MAX_BYTES = int(os.getenv("DJANGO_LOG_MAX_BYTES", str(10 * 1024 * 1024)))
_LOG_BACKUP_COUNT = int(os.getenv("DJANGO_LOG_BACKUP_COUNT", "5"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "file_line": {
            "format": "{levelname} {asctime} {name} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOGS_DIR / "django.log"),
            "maxBytes": _LOG_MAX_BYTES,
            "backupCount": _LOG_BACKUP_COUNT,
            "formatter": "file_line",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        "django": {
            "level": "INFO",
            "handlers": ["console", "file"],
            "propagate": False,
        },
        "django.request": {
            "level": "WARNING",
            "handlers": ["console", "file"],
            "propagate": False,
        },
        "apps.participants": {
            "level": "INFO",
            "handlers": ["console", "file"],
            "propagate": False,
        },
    },
    "root": {
        "level": "INFO",
        "handlers": ["console", "file"],
    },
}
