# Generated by Django 4.2.27 on 2026-01-30 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('church_role', models.CharField(max_length=50, verbose_name='직분')),
                ('age_group', models.CharField(max_length=20, verbose_name='연령대')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('register_type', models.CharField(choices=[('PRE', '사전등록'), ('ONSITE', '현장등록')], default='PRE', max_length=10, verbose_name='등록 유형')),
                ('payment_method', models.CharField(choices=[('BANK', '무통장'), ('CARD', '카드'), ('CASH', '현금')], default='BANK', max_length=10, verbose_name='결제 방식')),
                ('status', models.CharField(choices=[('PENDING', '입금대기'), ('PAID', '등록완료'), ('CANCEL_REQ', '환불요청'), ('CANCELLED', '취소완료'), ('REFUNDED', '환불완료')], default='PENDING', max_length=20, verbose_name='상태')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='고유 ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '참여자',
                'verbose_name_plural': '참여자 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
