# Generated by Django 4.2.27 on 2026-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='country',
            field=models.CharField(default='한국', max_length=50, verbose_name='나라'),
        ),
        migrations.AddField(
            model_name='participant',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='단체'),
        ),
    ]
