# Generated by Django 4.2.27 on 2026-01-30 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_participant_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age_group',
            field=models.CharField(db_comment='참가자의 연령대 (20대, 30대, 40대, 50대, 60대 이상)', help_text='참가자의 연령대 (20대, 30대, 40대, 50대, 60대 이상)', max_length=20, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='church_role',
            field=models.CharField(db_comment='교회 내 직분 (목사, 전도사, 장로, 집사, 권사, 성도 등)', help_text='교회 내 직분 (예: 목사, 전도사, 장로, 집사, 권사, 성도 등)', max_length=50, verbose_name='직분'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(db_comment='참가자의 국적 또는 거주 국가', default='한국', help_text='참가자의 국적 또는 거주 국가', max_length=50, verbose_name='나라'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='신청서가 등록된 날짜와 시간', help_text='신청서가 등록된 날짜와 시간', verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(db_comment='참가자의 이메일 주소 (중복 불가, 로그인 ID로 사용)', help_text='참가자의 이메일 주소 (중복 불가, 로그인 ID로 사용)', max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(db_comment='참가자의 성별 (남성, 여성)', help_text='참가자의 성별 (남성, 여성)', max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(db_comment='참가자의 실명', help_text='참가자의 실명을 입력합니다', max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='organization',
            field=models.CharField(blank=True, db_comment='소속 교회 또는 단체명 (선택 사항)', default='', help_text='소속 교회 또는 단체명 (선택 사항)', max_length=100, verbose_name='단체'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_method',
            field=models.CharField(choices=[('BANK', '무통장'), ('CARD', '카드'), ('CASH', '현금')], db_comment='결제 방식 (BANK:무통장, CARD:카드, CASH:현금)', default='BANK', help_text='무통장입금, 카드결제, 현금결제 중 선택', max_length=10, verbose_name='결제 방식'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(db_comment='참가자의 연락 가능한 전화번호 (010-0000-0000 형식)', help_text='참가자의 연락 가능한 전화번호 (010-0000-0000 형식)', max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='qr_image',
            field=models.ImageField(blank=True, db_comment='참가자 확인용 QR 코드 이미지 파일 경로', help_text='참가자 확인용 QR 코드 이미지 (자동 생성)', null=True, upload_to='qrcodes/', verbose_name='QR 코드'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='register_type',
            field=models.CharField(choices=[('PRE', '사전등록'), ('ONSITE', '현장등록')], db_comment='등록 유형 (PRE:사전등록, ONSITE:현장등록)', default='PRE', help_text='사전등록 또는 현장등록 구분', max_length=10, verbose_name='등록 유형'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('PENDING', '입금대기'), ('PAID', '등록완료'), ('CANCEL_REQ', '환불요청'), ('CANCELLED', '취소완료'), ('REFUNDED', '환불완료')], db_comment='신청 처리 상태 (PENDING:입금대기, PAID:등록완료, CANCEL_REQ:환불요청, CANCELLED:취소완료, REFUNDED:환불완료)', default='PENDING', help_text='참가 신청 처리 상태 (입금대기, 등록완료, 환불요청, 취소완료, 환불완료)', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='정보가 마지막으로 수정된 날짜와 시간', help_text='정보가 마지막으로 수정된 날짜와 시간', verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='uuid',
            field=models.UUIDField(db_comment='참가자의 고유 식별자 (자동 생성, QR 코드에 사용)', default=uuid.uuid4, editable=False, help_text='참가자의 고유 식별자 (자동 생성, QR 코드에 사용)', unique=True, verbose_name='고유 ID'),
        ),
    ]
