# Generated by Django 4.2.28 on 2026-03-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_participant_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='passport_english_name',
            field=models.CharField(db_comment='여권 영문명', default='', help_text='여권에 표기된 영문 이름', max_length=100, verbose_name='여권 영문명'),
        ),
        migrations.AddField(
            model_name='participant',
            name='passport_expiry_date',
            field=models.DateField(blank=True, db_comment='여권 만료일', help_text='여권 만료일 (YYYY-MM-DD)', null=True, verbose_name='여권 만료일'),
        ),
        migrations.AddField(
            model_name='participant',
            name='passport_number',
            field=models.CharField(db_comment='여권번호', default='', help_text='여권 번호', max_length=50, verbose_name='여권번호'),
        ),
        migrations.AddField(
            model_name='participant',
            name='resident_registration_number',
            field=models.CharField(blank=True, db_comment='주민등록번호 (보험용, 투어 후 파기)', default='', help_text='여행자 보험 가입용, 투어 종료 후 파기', max_length=20, verbose_name='주민등록번호'),
        ),
        migrations.AddField(
            model_name='participant',
            name='vision_trip_antioch',
            field=models.BooleanField(db_comment='비전트립 안디옥 선택 여부', default=False, verbose_name='안디옥(디스)'),
        ),
        migrations.AddField(
            model_name='participant',
            name='vision_trip_cappadocia',
            field=models.BooleanField(db_comment='비전트립 갑바도기아 선택 여부', default=False, verbose_name='갑바도기아'),
        ),
        migrations.AddField(
            model_name='participant',
            name='vision_trip_choice',
            field=models.CharField(choices=[('pre', 'B2N 일정 전'), ('post', 'B2N 일정 후'), ('none', '선택 안함')], db_comment='비전트립 선택 (pre/post/none)', default='none', help_text='B2N 일정 전/후/선택 안함', max_length=10, verbose_name='비전트립 선택'),
        ),
        migrations.AddField(
            model_name='participant',
            name='vision_trip_istanbul',
            field=models.BooleanField(db_comment='비전트립 이스탄불 선택 여부', default=False, verbose_name='이스탄불(체류)'),
        ),
    ]
