# Generated by Django 4.2.28 on 2026-03-03 09:18

from django.db import migrations


def rename_table_forward(apps, schema_editor):
    """
    이전 테이블명이 존재할 때만 participants로 rename.
    이미 participants가 있거나 old가 없으면 skip한다.
    """
    old_table = "participants_participant"
    new_table = "participants"
    tables = set(schema_editor.connection.introspection.table_names())

    if old_table in tables and new_table not in tables:
        model = apps.get_model("participants", "Participant")
        schema_editor.alter_db_table(model, old_table, new_table)


def rename_table_backward(apps, schema_editor):
    old_table = "participants_participant"
    new_table = "participants"
    tables = set(schema_editor.connection.introspection.table_names())

    if new_table in tables and old_table not in tables:
        model = apps.get_model("participants", "Participant")
        schema_editor.alter_db_table(model, new_table, old_table)


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_add_vision_trip_and_passport_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_table_forward, rename_table_backward),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="participant",
                    table="participants",
                ),
            ],
        ),
    ]
