"""API ErrorCode 상수 — PlanDoc/apiResponseRules.md 부록 A와 동일 값 유지."""


class ErrorCode:
    SUCCESS = "00"

    AUTH_REQUIRED = "10"
    TOKEN_EXPIRED = "11"
    TOKEN_MISSING = "12"
    TOKEN_INVALID = "13"
    REFRESH_TOKEN_ERROR = "14"
    LOGIN_FAILED = "15"

    PERMISSION_DENIED = "20"
    ADMIN_REQUIRED = "21"
    ACCESS_FORBIDDEN = "22"

    REQUIRED_FIELD_MISSING = "30"
    INVALID_INPUT = "31"
    INVALID_FORMAT = "32"
    LENGTH_EXCEEDED = "33"
    DUPLICATE_DATA = "34"

    DATA_NOT_FOUND = "40"
    RESOURCE_NOT_FOUND = "41"
    ALREADY_DELETED = "42"
    INVALID_STATE = "43"

    SERVER_ERROR = "50"
    DATABASE_ERROR = "51"
    EXTERNAL_API_ERROR = "52"
    PROCESSING_ERROR = "53"

    PAYMENT_FAILED = "60"
    PAYMENT_CANCELED = "61"
    PAYMENT_INVALID = "62"

    FILE_UPLOAD_FAILED = "70"
    INVALID_FILE_TYPE = "71"
    FILE_SIZE_EXCEEDED = "72"

    UNKNOWN_ERROR = "90"
    NOT_PROCESSABLE = "99"
